name: plexarr

networks:
  proxy:
    driver: bridge

x-common-env: &common-env
  PUID: 1000
  PGID: 1000
  TZ: America/Argentina/Buenos_Aires

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks: [proxy]

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    networks: [proxy]

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      <<: *common-env
      VERSION: docker
    volumes:
      - ./plex/config:/config
      - ./data/movies:/movies
      - ./data/tv:/tv
      - ./data/transcode:/transcode
    expose:
      - "32400"
    networks: [proxy]
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      <<: *common-env
      WEBUI_PORT: 8080
    volumes:
      - ./qbittorrent/config:/config
      - ./data/downloads:/downloads
    expose:
      - "8080"
    networks: [proxy]
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment: *common-env
    volumes:
      - ./prowlarr/config:/config
    expose:
      - "9696"
    networks: [proxy]
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment: *common-env
    volumes:
      - ./sonarr/config:/config
      - ./data/tv:/tv
      - ./data/downloads:/downloads
    expose:
      - "8989"
    networks: [proxy]
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - prowlarr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment: *common-env
    volumes:
      - ./radarr/config:/config
      - ./data/movies:/movies
      - ./data/downloads:/downloads
    expose:
      - "7878"
    networks: [proxy]
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - prowlarr

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment: *common-env
    volumes:
      - ./bazarr/config:/config
      - ./data/movies:/movies
      - ./data/tv:/tv
    expose:
      - "6767"
    networks: [proxy]
    restart: unless-stopped
    depends_on:
      - plex

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment: *common-env
    volumes:
      - ./tautulli/config:/config
    expose:
      - "8181"
    networks: [proxy]
    restart: unless-stopped
    depends_on:
      - plex
