name: infra

networks:
  proxy:
    external: true   # Connect to the same proxy network for NPM access

services:
  # --- Nginx Proxy Manager: reverse proxy + UI for domain mapping
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin UI
    volumes:
      - ${APPDATA_ROOT}/npm/data:/data
      - ${APPDATA_ROOT}/npm/letsencrypt:/etc/letsencrypt
    environment:
      TZ: ${TZ}
    networks: [proxy]

  # --- Pi-hole: DNS server + ad/tracker blocking
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "${NAS_IP}:53:53/tcp"    # DNS (TCP)
      - "${NAS_IP}:53:53/udp"    # DNS (UDP)
    environment:
      TZ: ${TZ}
      DNSMASQ_LISTENING: "all"    # Listen on all interfaces (Docker/LAN)
    volumes:
      - ${APPDATA_ROOT}/pihole/etc-pihole:/etc/pihole
      - ${APPDATA_ROOT}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks: [proxy]

  # --- Uptime Kuma: monitor uptime and Internet connectivity
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    dns:
      - "${NAS_IP}"   # Pi-hole DNS server
    expose:
      - "3001"   # Web UI (proxied through NPM)
    volumes:
      - ${APPDATA_ROOT}/uptime-kuma/data:/app/data
    environment:
      TZ: ${TZ}
    networks: [proxy]
