name: streaming

networks:
  proxy:
    external: true   # Connect Plex and Tautulli to proxy for NPM access

services:
  # --- Plex Media Server: stream movies and TV shows
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      VERSION: docker
    volumes:
      - ./plex/config:/config
      - ../data/movies:/movies
      - ../data/tv:/tv
      - ../data/transcode:/transcode   # optional SSD for better transcoding
    expose:
      - "32400"   # Plex main port
    networks: [proxy]

  # --- Tautulli: monitor Plex activity and stats
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./tautulli/config:/config
    expose:
      - "8181"   # Web UI
    networks: [proxy]
    depends_on:
      - plex
